"""Initial professional structure

Revision ID: d553ed1f3dfd
Revises: 
Create Date: 2026-06-30 15:17:15.239556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd553ed1f3dfd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('table_affected', sa.String(), nullable=False),
    sa.Column('data_old', sa.JSON(), nullable=True),
    sa.Column('data_new', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cedula', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drivers_cedula'), 'drivers', ['cedula'], unique=True)
    op.create_index(op.f('ix_drivers_id'), 'drivers', ['id'], unique=False)
    op.create_table('inspeccion_cajas_fuertes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('placa_vehiculo', sa.String(length=10), nullable=False),
    sa.Column('puerta_estado', sa.String(length=50), nullable=False),
    sa.Column('puerta_facilidad', sa.String(length=50), nullable=False),
    sa.Column('clave_precisa', sa.String(length=50), nullable=False),
    sa.Column('clave_autorizada', sa.String(length=50), nullable=False),
    sa.Column('perilla_funciona', sa.String(length=50), nullable=False),
    sa.Column('numeros_visibles', sa.String(length=50), nullable=False),
    sa.Column('caja_anclada', sa.String(length=50), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('fecha_inspeccion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspeccion_cajas_fuertes_id'), 'inspeccion_cajas_fuertes', ['id'], unique=False)
    op.create_index(op.f('ix_inspeccion_cajas_fuertes_placa_vehiculo'), 'inspeccion_cajas_fuertes', ['placa_vehiculo'], unique=False)
    op.create_table('inspecciones_botiquines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('placa_vehiculo', sa.String(length=10), nullable=False),
    sa.Column('gasas_limpias', sa.String(length=50), nullable=True),
    sa.Column('esparadrapo_tela', sa.String(length=50), nullable=True),
    sa.Column('baja_lenguas', sa.String(length=50), nullable=True),
    sa.Column('guantes_latex', sa.String(length=50), nullable=True),
    sa.Column('venda_elastica_2', sa.String(length=50), nullable=True),
    sa.Column('venda_elastica_3', sa.String(length=50), nullable=True),
    sa.Column('venda_elastica_5', sa.String(length=50), nullable=True),
    sa.Column('venda_algodon', sa.String(length=50), nullable=True),
    sa.Column('yodopovidona', sa.String(length=50), nullable=True),
    sa.Column('solucion_salina', sa.String(length=50), nullable=True),
    sa.Column('termometro_digital', sa.String(length=50), nullable=True),
    sa.Column('alcohol_antiseptico', sa.String(length=50), nullable=True),
    sa.Column('botella_agua', sa.String(length=50), nullable=True),
    sa.Column('bandas_adhesivas', sa.String(length=50), nullable=True),
    sa.Column('tijeras_punta_roma', sa.String(length=50), nullable=True),
    sa.Column('pito_emergencias', sa.String(length=50), nullable=True),
    sa.Column('manual_primeros_auxilios', sa.String(length=50), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('fecha_inspeccion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspecciones_botiquines_id'), 'inspecciones_botiquines', ['id'], unique=False)
    op.create_index(op.f('ix_inspecciones_botiquines_placa_vehiculo'), 'inspecciones_botiquines', ['placa_vehiculo'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('tbl_cashless',
    sa.Column('codigo', sa.Integer(), nullable=False),
    sa.Column('cliente', sa.String(length=255), nullable=False),
    sa.Column('dt', sa.Integer(), nullable=False),
    sa.Column('placa', sa.String(length=20), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('novedad', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('codigo')
    )
    op.create_index(op.f('ix_tbl_cashless_codigo'), 'tbl_cashless', ['codigo'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firebase_uid', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_firebase_uid'), 'users', ['firebase_uid'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plate', sa.String(), nullable=False),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_id'), 'vehicles', ['id'], unique=False)
    op.create_index(op.f('ix_vehicles_plate'), 'vehicles', ['plate'], unique=True)
    op.create_table('driver_courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('finish_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_driver_courses_id'), 'driver_courses', ['id'], unique=False)
    op.create_table('fines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fines_id'), 'fines', ['id'], unique=False)
    op.create_table('licenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('expiration_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_licenses_id'), 'licenses', ['id'], unique=False)
    op.create_table('maintenance_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_records_id'), 'maintenance_records', ['id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('vehicle_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('document_type', sa.String(), nullable=False),
    sa.Column('expiration_date', sa.Date(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_documents_id'), 'vehicle_documents', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicle_documents_id'), table_name='vehicle_documents')
    op.drop_table('vehicle_documents')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_maintenance_records_id'), table_name='maintenance_records')
    op.drop_table('maintenance_records')
    op.drop_index(op.f('ix_licenses_id'), table_name='licenses')
    op.drop_table('licenses')
    op.drop_index(op.f('ix_fines_id'), table_name='fines')
    op.drop_table('fines')
    op.drop_index(op.f('ix_driver_courses_id'), table_name='driver_courses')
    op.drop_table('driver_courses')
    op.drop_index(op.f('ix_vehicles_plate'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_id'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_firebase_uid'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tbl_cashless_codigo'), table_name='tbl_cashless')
    op.drop_table('tbl_cashless')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_inspecciones_botiquines_placa_vehiculo'), table_name='inspecciones_botiquines')
    op.drop_index(op.f('ix_inspecciones_botiquines_id'), table_name='inspecciones_botiquines')
    op.drop_table('inspecciones_botiquines')
    op.drop_index(op.f('ix_inspeccion_cajas_fuertes_placa_vehiculo'), table_name='inspeccion_cajas_fuertes')
    op.drop_index(op.f('ix_inspeccion_cajas_fuertes_id'), table_name='inspeccion_cajas_fuertes')
    op.drop_table('inspeccion_cajas_fuertes')
    op.drop_index(op.f('ix_drivers_id'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_cedula'), table_name='drivers')
    op.drop_table('drivers')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
